// flow-typed signature: e67b8977cea44408699e9195ea66bac6
// flow-typed version: <<STUB>>/mqtt_v2.18.8/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mqtt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mqtt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mqtt/bin/pub' {
  declare module.exports: any;
}

declare module 'mqtt/bin/sub' {
  declare module.exports: any;
}

declare module 'mqtt/dist/mqtt' {
  declare module.exports: any;
}

declare module 'mqtt/dist/mqtt.min' {
  declare module.exports: any;
}

declare module 'mqtt/examples/client/secure-client' {
  declare module.exports: any;
}

declare module 'mqtt/examples/client/simple-both' {
  declare module.exports: any;
}

declare module 'mqtt/examples/client/simple-publish' {
  declare module.exports: any;
}

declare module 'mqtt/examples/client/simple-subscribe' {
  declare module.exports: any;
}

declare module 'mqtt/examples/tls client/mqttclient' {
  declare module.exports: any;
}

declare module 'mqtt/examples/wss/client_with_proxy' {
  declare module.exports: any;
}

declare module 'mqtt/examples/wss/client' {
  declare module.exports: any;
}

declare module 'mqtt/lib/client' {
  declare module.exports: any;
}

declare module 'mqtt/lib/connect/index' {
  declare module.exports: any;
}

declare module 'mqtt/lib/connect/tcp' {
  declare module.exports: any;
}

declare module 'mqtt/lib/connect/tls' {
  declare module.exports: any;
}

declare module 'mqtt/lib/connect/ws' {
  declare module.exports: any;
}

declare module 'mqtt/lib/connect/wx' {
  declare module.exports: any;
}

declare module 'mqtt/lib/store' {
  declare module.exports: any;
}

declare module 'mqtt/lib/validations' {
  declare module.exports: any;
}

declare module 'mqtt/mqtt' {
  declare module.exports: any;
}

declare module 'mqtt/test/abstract_client' {
  declare module.exports: any;
}

declare module 'mqtt/test/abstract_store' {
  declare module.exports: any;
}

declare module 'mqtt/test/browser/server' {
  declare module.exports: any;
}

declare module 'mqtt/test/browser/test' {
  declare module.exports: any;
}

declare module 'mqtt/test/browser/wx' {
  declare module.exports: any;
}

declare module 'mqtt/test/client' {
  declare module.exports: any;
}

declare module 'mqtt/test/helpers/server_process' {
  declare module.exports: any;
}

declare module 'mqtt/test/helpers/server' {
  declare module.exports: any;
}

declare module 'mqtt/test/mqtt_store' {
  declare module.exports: any;
}

declare module 'mqtt/test/mqtt' {
  declare module.exports: any;
}

declare module 'mqtt/test/secure_client' {
  declare module.exports: any;
}

declare module 'mqtt/test/server' {
  declare module.exports: any;
}

declare module 'mqtt/test/store' {
  declare module.exports: any;
}

declare module 'mqtt/test/typescript/broker-connect-subscribe-and-publish' {
  declare module.exports: any;
}

declare module 'mqtt/test/util' {
  declare module.exports: any;
}

declare module 'mqtt/test/websocket_client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mqtt/bin/pub.js' {
  declare module.exports: $Exports<'mqtt/bin/pub'>;
}
declare module 'mqtt/bin/sub.js' {
  declare module.exports: $Exports<'mqtt/bin/sub'>;
}
declare module 'mqtt/dist/mqtt.js' {
  declare module.exports: $Exports<'mqtt/dist/mqtt'>;
}
declare module 'mqtt/dist/mqtt.min.js' {
  declare module.exports: $Exports<'mqtt/dist/mqtt.min'>;
}
declare module 'mqtt/examples/client/secure-client.js' {
  declare module.exports: $Exports<'mqtt/examples/client/secure-client'>;
}
declare module 'mqtt/examples/client/simple-both.js' {
  declare module.exports: $Exports<'mqtt/examples/client/simple-both'>;
}
declare module 'mqtt/examples/client/simple-publish.js' {
  declare module.exports: $Exports<'mqtt/examples/client/simple-publish'>;
}
declare module 'mqtt/examples/client/simple-subscribe.js' {
  declare module.exports: $Exports<'mqtt/examples/client/simple-subscribe'>;
}
declare module 'mqtt/examples/tls client/mqttclient.js' {
  declare module.exports: $Exports<'mqtt/examples/tls client/mqttclient'>;
}
declare module 'mqtt/examples/wss/client_with_proxy.js' {
  declare module.exports: $Exports<'mqtt/examples/wss/client_with_proxy'>;
}
declare module 'mqtt/examples/wss/client.js' {
  declare module.exports: $Exports<'mqtt/examples/wss/client'>;
}
declare module 'mqtt/lib/client.js' {
  declare module.exports: $Exports<'mqtt/lib/client'>;
}
declare module 'mqtt/lib/connect/index.js' {
  declare module.exports: $Exports<'mqtt/lib/connect/index'>;
}
declare module 'mqtt/lib/connect/tcp.js' {
  declare module.exports: $Exports<'mqtt/lib/connect/tcp'>;
}
declare module 'mqtt/lib/connect/tls.js' {
  declare module.exports: $Exports<'mqtt/lib/connect/tls'>;
}
declare module 'mqtt/lib/connect/ws.js' {
  declare module.exports: $Exports<'mqtt/lib/connect/ws'>;
}
declare module 'mqtt/lib/connect/wx.js' {
  declare module.exports: $Exports<'mqtt/lib/connect/wx'>;
}
declare module 'mqtt/lib/store.js' {
  declare module.exports: $Exports<'mqtt/lib/store'>;
}
declare module 'mqtt/lib/validations.js' {
  declare module.exports: $Exports<'mqtt/lib/validations'>;
}
declare module 'mqtt/mqtt.js' {
  declare module.exports: $Exports<'mqtt/mqtt'>;
}
declare module 'mqtt/test/abstract_client.js' {
  declare module.exports: $Exports<'mqtt/test/abstract_client'>;
}
declare module 'mqtt/test/abstract_store.js' {
  declare module.exports: $Exports<'mqtt/test/abstract_store'>;
}
declare module 'mqtt/test/browser/server.js' {
  declare module.exports: $Exports<'mqtt/test/browser/server'>;
}
declare module 'mqtt/test/browser/test.js' {
  declare module.exports: $Exports<'mqtt/test/browser/test'>;
}
declare module 'mqtt/test/browser/wx.js' {
  declare module.exports: $Exports<'mqtt/test/browser/wx'>;
}
declare module 'mqtt/test/client.js' {
  declare module.exports: $Exports<'mqtt/test/client'>;
}
declare module 'mqtt/test/helpers/server_process.js' {
  declare module.exports: $Exports<'mqtt/test/helpers/server_process'>;
}
declare module 'mqtt/test/helpers/server.js' {
  declare module.exports: $Exports<'mqtt/test/helpers/server'>;
}
declare module 'mqtt/test/mqtt_store.js' {
  declare module.exports: $Exports<'mqtt/test/mqtt_store'>;
}
declare module 'mqtt/test/mqtt.js' {
  declare module.exports: $Exports<'mqtt/test/mqtt'>;
}
declare module 'mqtt/test/secure_client.js' {
  declare module.exports: $Exports<'mqtt/test/secure_client'>;
}
declare module 'mqtt/test/server.js' {
  declare module.exports: $Exports<'mqtt/test/server'>;
}
declare module 'mqtt/test/store.js' {
  declare module.exports: $Exports<'mqtt/test/store'>;
}
declare module 'mqtt/test/typescript/broker-connect-subscribe-and-publish.js' {
  declare module.exports: $Exports<'mqtt/test/typescript/broker-connect-subscribe-and-publish'>;
}
declare module 'mqtt/test/util.js' {
  declare module.exports: $Exports<'mqtt/test/util'>;
}
declare module 'mqtt/test/websocket_client.js' {
  declare module.exports: $Exports<'mqtt/test/websocket_client'>;
}
