// flow-typed signature: 40526ed76913d68bd24c93682ca24a50
// flow-typed version: <<STUB>>/stompjs_vgit://github.com/gfoiani/stomp-websocket.git#2.4.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stompjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stompjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stompjs/browsertests/integration/integration' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/qunit' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/ack' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/config' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/connection' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/frame' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/message' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/parse_connect' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/subscription' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/transaction' {
  declare module.exports: any;
}

declare module 'stompjs/browsertests/unit/websocket' {
  declare module.exports: any;
}

declare module 'stompjs/doc/j/doc' {
  declare module.exports: any;
}

declare module 'stompjs/example/server' {
  declare module.exports: any;
}

declare module 'stompjs/example/webworker/webworker' {
  declare module.exports: any;
}

declare module 'stompjs/lib/stomp-node' {
  declare module.exports: any;
}

declare module 'stompjs/lib/stomp' {
  declare module.exports: any;
}

declare module 'stompjs/lib/stomp.min' {
  declare module.exports: any;
}

declare module 'stompjs/spec/server.mock' {
  declare module.exports: any;
}

declare module 'stompjs/spec/stomp-node.spec' {
  declare module.exports: any;
}

declare module 'stompjs/spec/stomp.spec' {
  declare module.exports: any;
}

declare module 'stompjs/spec/websocket.mock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stompjs/browsertests/integration/integration.js' {
  declare module.exports: $Exports<'stompjs/browsertests/integration/integration'>;
}
declare module 'stompjs/browsertests/qunit.js' {
  declare module.exports: $Exports<'stompjs/browsertests/qunit'>;
}
declare module 'stompjs/browsertests/unit/ack.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/ack'>;
}
declare module 'stompjs/browsertests/unit/config.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/config'>;
}
declare module 'stompjs/browsertests/unit/connection.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/connection'>;
}
declare module 'stompjs/browsertests/unit/frame.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/frame'>;
}
declare module 'stompjs/browsertests/unit/message.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/message'>;
}
declare module 'stompjs/browsertests/unit/parse_connect.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/parse_connect'>;
}
declare module 'stompjs/browsertests/unit/subscription.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/subscription'>;
}
declare module 'stompjs/browsertests/unit/transaction.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/transaction'>;
}
declare module 'stompjs/browsertests/unit/websocket.js' {
  declare module.exports: $Exports<'stompjs/browsertests/unit/websocket'>;
}
declare module 'stompjs/doc/j/doc.js' {
  declare module.exports: $Exports<'stompjs/doc/j/doc'>;
}
declare module 'stompjs/example/server.js' {
  declare module.exports: $Exports<'stompjs/example/server'>;
}
declare module 'stompjs/example/webworker/webworker.js' {
  declare module.exports: $Exports<'stompjs/example/webworker/webworker'>;
}
declare module 'stompjs/index' {
  declare module.exports: $Exports<'stompjs'>;
}
declare module 'stompjs/index.js' {
  declare module.exports: $Exports<'stompjs'>;
}
declare module 'stompjs/lib/stomp-node.js' {
  declare module.exports: $Exports<'stompjs/lib/stomp-node'>;
}
declare module 'stompjs/lib/stomp.js' {
  declare module.exports: $Exports<'stompjs/lib/stomp'>;
}
declare module 'stompjs/lib/stomp.min.js' {
  declare module.exports: $Exports<'stompjs/lib/stomp.min'>;
}
declare module 'stompjs/spec/server.mock.js' {
  declare module.exports: $Exports<'stompjs/spec/server.mock'>;
}
declare module 'stompjs/spec/stomp-node.spec.js' {
  declare module.exports: $Exports<'stompjs/spec/stomp-node.spec'>;
}
declare module 'stompjs/spec/stomp.spec.js' {
  declare module.exports: $Exports<'stompjs/spec/stomp.spec'>;
}
declare module 'stompjs/spec/websocket.mock.js' {
  declare module.exports: $Exports<'stompjs/spec/websocket.mock'>;
}
