// flow-typed signature: a3cdab1904e44ce4d8d34b920ac059b5
// flow-typed version: <<STUB>>/uuid-v4_v0.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-v4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-v4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uuid-v4/index' {
  declare module.exports: $Exports<'uuid-v4'>;
}
declare module 'uuid-v4/index.js' {
  declare module.exports: $Exports<'uuid-v4'>;
}
